sudo: required
services:
  - docker

before_install:
  - docker build -t unusualcaspento/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true unusualcaspento/docker-react npm run test
language: generic

deploy:
  provider: elasticbeanstalk